name: emergency_numbers
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1


environment:
  sdk: '>=2.19.4 <3.0.0'



dependencies:
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - Assets/pstation.png
    - Assets/fire.png
    - Assets/hospt.png
    - Assets/rab.png
    - Assets/ambulance.png
    - Assets/doctor.png
